"""Generate SCHEMA.md -- the plain-English-query reference to every workspace DB.

Reuses db_dashboard's MANIFEST so it never drifts. Regenerate after adding data:
    python schema_doc.py
"""
from __future__ import annotations

import sqlite3

from db_dashboard import HERE, INTERNAL, MANIFEST, WORKSPACE

OUT = HERE / "SCHEMA.md"

PREAMBLE = """\
# Workspace sports-data schema reference

_Auto-generated by `schema_doc.py`: regenerate after adding data. Do not hand-edit._

This is the map Claude consults to answer sports questions in plain English. To
answer one:

1. Pick the database for the sport (sections below).
2. Read its table/column list here; don't guess column names.
3. Write read-only SQL and run it against the DB path with python + sqlite3.
4. Validate against a known fact (a famous result/number) before reporting.

All paths are relative to the workspace root (the directory containing this repo).
"""

# Static, because it describes databases this script cannot introspect: the
# canonical NBA/NFL/NHL/MLB copies live on homebase, not on the PC. It was
# hand-written into SCHEMA.md on 2026-09-22 until review caught that the next
# regeneration (OP-4, mandatory after any refresh) would silently drop it.
# Re-measure the dated figures when you change it.
HOMEBASE = """\
## Which copy is canonical

The tables below are introspected from the PC copies. For NBA, NFL, NHL and MLB
games those copies are a frozen fork from the 2026-09-20 migration; the canonical,
daily-updated databases are on homebase, written at 06:10 by `sports-crons`.
Query them with the recipe in [`CLAUDE.md`](CLAUDE.md) ("Querying homebase"),
opened `?mode=ro&immutable=1`. Measured 2026-09-22:

| League | Homebase (canonical) | Last final | PC fork | PC last final |
|---|---|---|---|---|
| NBA | `/opt/data/sports/nba/data/nba.db` | 2026-06-13 | `data_explorer/nba/data/nba.db` | 2026-06-13 (offseason; diverges in October) |
| NFL | `/opt/data/sports/nfl/data/nfl.db` | 2026-09-21 | `data_explorer/nfl/data/nfl.db` | 2026-02-08 |
| NHL | `/opt/data/sports/nhl/data/nhl.db` | 2026-06-14 | `data_explorer/nhl/data/nhl.db` | 2026-06-14 (offseason; diverges in October) |
| MLB games | `/opt/data/sports/mlb/data/mlb.db` | 2026-09-21 | none | n/a |

PGA, sumo, MLB draft, NBA comebacks and podcasts exist only on the PC and have no
scheduled writer. Freshness: `/opt/data/sports/_status/<league>.json`
(`last_success`, `consecutive_failures`, `outcome`). The `sports-data` MCP
server read the PC fork only and was removed from `.mcp.json` 2026-09-23; use
the `sports-analyst` agent, which reads homebase directly.

Homebase schemas match the PC tables for NBA and NHL. NFL `player_game` and
`team_game` carry 35 extra columns on homebase. NFL and MLB `games` also hold
scheduled and postponed rows with NULL scores (NFL 240, MLB 185 on 2026-09-22;
NHL none), so filter `home_score IS NOT NULL`.

### MLB games (homebase only): `/opt/data/sports/mlb/data/mlb.db`
> `status` counts on 2026-09-22: `F` 119,485, `C` 149, `R` 2, `D` 1 (the `D` row is a 2026-09-22 game with no score yet). 35 `F` rows have NULL scores, so a completed-game filter is `status = 'F' AND home_score IS NOT NULL`. Games key on `game_pk`; join players and teams on `player_id` / `team_id`.

- **games** (119,637 rows): game_pk INTEGER, season INTEGER, game_type TEXT, game_date TEXT, home_team_id INTEGER, away_team_id INTEGER, home_score INTEGER, away_score INTEGER, venue_id INTEGER, venue_name TEXT, day_night TEXT, doubleheader TEXT, game_number INTEGER, status TEXT
- **player_game_batting** (2,532,647 rows): game_pk INTEGER, player_id INTEGER, team_id INTEGER, season INTEGER, game_date TEXT, game_type TEXT, batting_order INTEGER, position TEXT, at_bats INTEGER, runs INTEGER, hits INTEGER, doubles INTEGER, triples INTEGER, home_runs INTEGER, rbi INTEGER, base_on_balls INTEGER, intentional_walks INTEGER, strike_outs INTEGER, stolen_bases INTEGER, caught_stealing INTEGER, hit_by_pitch INTEGER, sac_flies INTEGER, sac_bunts INTEGER, ground_into_double_play INTEGER, plate_appearances INTEGER, total_bases INTEGER, left_on_base INTEGER
- **player_game_pitching** (839,383 rows): game_pk INTEGER, player_id INTEGER, team_id INTEGER, season INTEGER, game_date TEXT, game_type TEXT, outs INTEGER, batters_faced INTEGER, hits INTEGER, runs INTEGER, earned_runs INTEGER, home_runs INTEGER, base_on_balls INTEGER, intentional_walks INTEGER, strike_outs INTEGER, hit_by_pitch INTEGER, number_of_pitches INTEGER, strikes INTEGER, balls INTEGER, games_started INTEGER, wins INTEGER, losses INTEGER, saves INTEGER, holds INTEGER, blown_saves INTEGER
- **players** (11,287 rows): player_id INTEGER, player_name TEXT
- **team_game** (239,274 rows): game_pk INTEGER, team_id INTEGER, opponent_team_id INTEGER, is_home INTEGER, season INTEGER, game_date TEXT, game_type TEXT, runs INTEGER, hits INTEGER, errors INTEGER, at_bats INTEGER, doubles INTEGER, triples INTEGER, home_runs INTEGER, rbi INTEGER, base_on_balls INTEGER, strike_outs INTEGER, stolen_bases INTEGER, left_on_base INTEGER, total_bases INTEGER
- **teams** (30 rows): team_id INTEGER, abbreviation TEXT, name TEXT
"""

# Per-database query notes, keyed by the MANIFEST path. Table/column lists are
# introspected, but the *join conventions and known confounds* are not knowable
# from the schema, and getting them wrong produces confidently wrong answers.
# Keep each note to what changes the SQL you would write.
NOTES: dict[str, list[str]] = {
    "data_explorer/nba/data/nba.db": [
        "**`season_type` has three values:** `Regular Season`, `PlayIn` (2020-21 on) and "
        "`Playoffs`. Select playoffs with `season_type = 'Playoffs'`, never "
        "`!= 'Regular Season'`, which would count play-in games as playoff games.",
        "**Neutral-site games are in `games`** with the NBA's designated home team, so "
        "`games` holds one row per game with two `team_game` rows in every season.",
    ],
    "data_explorer/sumo/data/sumo.db": [
        "**Query `bout_wrestler`, not `bouts`.** It is the analysis-ready table: two rows "
        "per bout (one per wrestler's point of view), so win rate by any attribute is a "
        "one-line `GROUP BY` and the overall win rate is exactly 50% by construction "
        "(a built-in consistency check).",
        "**`as_of_physical` join convention.** `measurements` holds *change-points*, not "
        "one row per tournament. Never join a bout to a wrestler's career-latest weight: "
        "the physicals on `bout_wrestler` are already resolved as-of the bout's `basho_id` "
        "(most-recent-measurement-at-or-before, falling back to the earliest recorded for "
        "bouts that predate it). 95.6% of rows resolve a weight; the rest are NULL, never 0.",
        "**Exclude `kimarite = 'fusen'`**: those are forfeits where a wrestler was absent "
        "and no sumo happened, not physical contests.",
        "**Known caveat: marginal-mass claims are rank-confounded.** Win rate by *absolute* "
        "`weight_kg` (or `bmi`) mostly measures rank: heavier men are disproportionately "
        "higher-ranked, and rank predicts winning. Only the *differential* columns "
        "(`weight_adv`, `height_adv`, `bmi_adv`, `age_adv` = own minus opponent) are "
        "matchup-internal and safe to read causally. Any 'every extra kg is worth X%' claim "
        "must control on `rank_value` / `rank_adv` before it means anything.",
    ],
}


def _tables(conn: sqlite3.Connection) -> list[tuple[str, object, list[str]]]:
    names = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        if r[0] not in INTERNAL]
    out = []
    for t in names:
        cols = [f"{r[1]} {r[2]}".strip() for r in conn.execute(f"PRAGMA table_info('{t}')")]
        try:
            n = conn.execute(f"SELECT COUNT(*) FROM '{t}'").fetchone()[0]
        except sqlite3.Error:
            n = "?"
        out.append((t, n, cols))
    return out


def main() -> None:
    lines = [PREAMBLE, HOMEBASE]
    by_cat: dict[str, list[tuple[str, str]]] = {}
    for label, cat, rel in MANIFEST:
        by_cat.setdefault(cat, []).append((label, rel))

    for cat, items in by_cat.items():
        lines.append(f"\n## {cat}")
        for label, rel in items:
            path = WORKSPACE / rel
            lines.append(f"\n### {label}: `{rel}`")
            notes = NOTES.get(rel, [])
            if notes:
                # One blockquote, blank-quote lines between notes, then a real
                # blank line so the table list below isn't swallowed as lazy
                # blockquote continuation.
                lines.append("\n>\n".join(f"> {n}" for n in notes) + "\n")
            if not path.exists():
                lines.append("_(database file not found: run its scraper)_")
                continue
            conn = sqlite3.connect(path)
            try:
                for t, n, cols in _tables(conn):
                    count = f"{n:,} rows" if isinstance(n, int) else "rows"
                    lines.append(f"- **{t}** ({count}): {', '.join(cols)}")
            finally:
                conn.close()

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(MANIFEST)} databases)")


if __name__ == "__main__":
    main()
