"""Generate SCHEMA.md -- the plain-English-query reference to every workspace DB.

Reuses db_dashboard's MANIFEST so it never drifts. Regenerate after adding data:
    python schema_doc.py
"""
from __future__ import annotations

import sqlite3

from db_dashboard import HERE, INTERNAL, MANIFEST, WORKSPACE

OUT = HERE / "SCHEMA.md"

PREAMBLE = """\
# Workspace sports-data schema reference

_Auto-generated by `schema_doc.py` — regenerate after adding data. Do not hand-edit._

This is the map Claude consults to answer sports questions in plain English. To
answer one:

1. Pick the database for the sport (sections below).
2. Read its table/column list here — don't guess column names.
3. Write read-only SQL and run it against the DB path with python + sqlite3.
4. Validate against a known fact (a famous result/number) before reporting.

All paths are relative to the workspace root (the directory containing this repo).
"""

# Per-database query notes, keyed by the MANIFEST path. Table/column lists are
# introspected, but the *join conventions and known confounds* are not knowable
# from the schema — and getting them wrong produces confidently wrong answers.
# Keep each note to what changes the SQL you would write.
NOTES: dict[str, list[str]] = {
    "data_explorer/sumo/data/sumo.db": [
        "**Query `bout_wrestler`, not `bouts`.** It is the analysis-ready table: two rows "
        "per bout (one per wrestler's point of view), so win rate by any attribute is a "
        "one-line `GROUP BY` and the overall win rate is exactly 50% by construction "
        "(a built-in consistency check).",
        "**`as_of_physical` join convention.** `measurements` holds *change-points*, not "
        "one row per tournament. Never join a bout to a wrestler's career-latest weight — "
        "the physicals on `bout_wrestler` are already resolved as-of the bout's `basho_id` "
        "(most-recent-measurement-at-or-before, falling back to the earliest recorded for "
        "bouts that predate it). 95.6% of rows resolve a weight; the rest are NULL, never 0.",
        "**Exclude `kimarite = 'fusen'`** — those are forfeits where a wrestler was absent "
        "and no sumo happened, not physical contests.",
        "**Known caveat — marginal-mass claims are rank-confounded.** Win rate by *absolute* "
        "`weight_kg` (or `bmi`) mostly measures rank: heavier men are disproportionately "
        "higher-ranked, and rank predicts winning. Only the *differential* columns "
        "(`weight_adv`, `height_adv`, `bmi_adv`, `age_adv` = own minus opponent) are "
        "matchup-internal and safe to read causally. Any 'every extra kg is worth X%' claim "
        "must control on `rank_value` / `rank_adv` before it means anything.",
    ],
}


def _tables(conn: sqlite3.Connection) -> list[tuple[str, object, list[str]]]:
    names = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        if r[0] not in INTERNAL]
    out = []
    for t in names:
        cols = [f"{r[1]} {r[2]}".strip() for r in conn.execute(f"PRAGMA table_info('{t}')")]
        try:
            n = conn.execute(f"SELECT COUNT(*) FROM '{t}'").fetchone()[0]
        except sqlite3.Error:
            n = "?"
        out.append((t, n, cols))
    return out


def main() -> None:
    lines = [PREAMBLE]
    by_cat: dict[str, list[tuple[str, str]]] = {}
    for label, cat, rel in MANIFEST:
        by_cat.setdefault(cat, []).append((label, rel))

    for cat, items in by_cat.items():
        lines.append(f"\n## {cat}")
        for label, rel in items:
            path = WORKSPACE / rel
            lines.append(f"\n### {label} — `{rel}`")
            notes = NOTES.get(rel, [])
            if notes:
                # One blockquote, blank-quote lines between notes, then a real
                # blank line so the table list below isn't swallowed as lazy
                # blockquote continuation.
                lines.append("\n>\n".join(f"> {n}" for n in notes) + "\n")
            if not path.exists():
                lines.append("_(database file not found — run its scraper)_")
                continue
            conn = sqlite3.connect(path)
            try:
                for t, n, cols in _tables(conn):
                    count = f"{n:,} rows" if isinstance(n, int) else "rows"
                    lines.append(f"- **{t}** ({count}): {', '.join(cols)}")
            finally:
                conn.close()

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(MANIFEST)} databases)")


if __name__ == "__main__":
    main()
