"""Generate SCHEMA.md -- the plain-English-query reference to every workspace DB.

Reuses db_dashboard's MANIFEST so it never drifts. Regenerate after adding data:
    python schema_doc.py
"""
from __future__ import annotations

import sqlite3

from db_dashboard import HERE, INTERNAL, MANIFEST, WORKSPACE

OUT = HERE / "SCHEMA.md"

PREAMBLE = """\
# Workspace sports-data schema reference

_Auto-generated by `schema_doc.py` — regenerate after adding data. Do not hand-edit._

This is the map Claude consults to answer sports questions in plain English. To
answer one:

1. Pick the database for the sport (sections below).
2. Read its table/column list here — don't guess column names.
3. Write read-only SQL and run it against the DB path with python + sqlite3.
4. Validate against a known fact (a famous result/number) before reporting.

All paths are relative to the workspace root (`{workspace}`).
"""


def _tables(conn: sqlite3.Connection) -> list[tuple[str, object, list[str]]]:
    names = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        if r[0] not in INTERNAL]
    out = []
    for t in names:
        cols = [f"{r[1]} {r[2]}".strip() for r in conn.execute(f"PRAGMA table_info('{t}')")]
        try:
            n = conn.execute(f"SELECT COUNT(*) FROM '{t}'").fetchone()[0]
        except sqlite3.Error:
            n = "?"
        out.append((t, n, cols))
    return out


def main() -> None:
    lines = [PREAMBLE.format(workspace=WORKSPACE)]
    by_cat: dict[str, list[tuple[str, str]]] = {}
    for label, cat, rel in MANIFEST:
        by_cat.setdefault(cat, []).append((label, rel))

    for cat, items in by_cat.items():
        lines.append(f"\n## {cat}")
        for label, rel in items:
            path = WORKSPACE / rel
            lines.append(f"\n### {label} — `{rel}`")
            if not path.exists():
                lines.append("_(database file not found — run its scraper)_")
                continue
            conn = sqlite3.connect(path)
            try:
                for t, n, cols in _tables(conn):
                    count = f"{n:,} rows" if isinstance(n, int) else "rows"
                    lines.append(f"- **{t}** ({count}): {', '.join(cols)}")
            finally:
                conn.close()

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(MANIFEST)} databases)")


if __name__ == "__main__":
    main()
