// Auto-generated by mitchell_profile.py — do not edit manually
const MITCHELL_DATA = {
  "season": "2024-25",
  "ordered": [
    "Donovan Mitchell",
    "Cade Cunningham",
    "Bam Adebayo",
    "Pascal Siakam",
    "Tyrese Haliburton",
    "LaMelo Ball",
    "Zach LaVine",
    "Devin Booker",
    "Julius Randle",
    "Paolo Banchero",
    "Darius Garland"
  ],
  "players": {
    "Donovan Mitchell": {
      "player_id": 1628378,
      "gp": 71,
      "ppg": 24.0,
      "rpg": 4.5,
      "apg": 5.0,
      "spg": 1.3,
      "bpg": 0.2,
      "fg_pct": 44.3,
      "fg3_pct": 36.8,
      "ft_pct": 82.3,
      "ts_pct": 57.5,
      "usg_pct": 29.8,
      "pie": 13.7,
      "career": {
        "rs_career": {
          "GP": 609,
          "PPG": 25.1,
          "RPG": 4.3,
          "APG": 4.8
        },
        "playoff_career": {
          "GP": 81,
          "PPG": 27.8,
          "RPG": 5.0,
          "APG": 4.4
        }
      },
      "clutch": {
        "s0": {
          "label": "2024-25",
          "gp": 71,
          "ppg": 24.0,
          "fg_pct": 44.3,
          "w_pct": 77.5
        },
        "s1": {
          "label": "2024-25",
          "gp": 19,
          "ppg": 2.2,
          "fg_pct": 40.0,
          "w_pct": 47.4
        },
        "s2": {
          "label": "2024-25",
          "gp": 18,
          "ppg": 1.7,
          "fg_pct": 43.5,
          "w_pct": 44.4
        },
        "s3": {
          "label": "2024-25",
          "gp": 11,
          "ppg": 1.1,
          "fg_pct": 20.0,
          "w_pct": 27.3
        },
        "s4": {
          "label": "2024-25",
          "gp": 7,
          "ppg": 0.3,
          "fg_pct": 14.3,
          "w_pct": 14.3
        },
        "s5": {
          "label": "2024-25",
          "gp": 5,
          "ppg": 0.4,
          "fg_pct": 20.0,
          "w_pct": 20.0
        },
        "s6": {
          "label": "2024-25",
          "gp": 31,
          "ppg": 2.8,
          "fg_pct": 36.7,
          "w_pct": 67.7
        },
        "s7": {
          "label": "2024-25",
          "gp": 30,
          "ppg": 2.3,
          "fg_pct": 39.5,
          "w_pct": 66.7
        },
        "s8": {
          "label": "2024-25",
          "gp": 23,
          "ppg": 1.5,
          "fg_pct": 15.8,
          "w_pct": 65.2
        },
        "s9": {
          "label": "2024-25",
          "gp": 15,
          "ppg": 0.9,
          "fg_pct": 11.1,
          "w_pct": 60.0
        },
        "s10": {
          "label": "2024-25",
          "gp": 9,
          "ppg": 0.7,
          "fg_pct": 16.7,
          "w_pct": 55.6
        }
      }
    },
    "Cade Cunningham": {
      "player_id": 1630595,
      "gp": 70,
      "ppg": 26.1,
      "rpg": 6.1,
      "apg": 9.1,
      "spg": 1.0,
      "bpg": 0.8,
      "fg_pct": 46.9,
      "fg3_pct": 35.6,
      "ft_pct": 84.6,
      "ts_pct": 56.5,
      "usg_pct": 32.3,
      "pie": 15.2,
      "career": {
        "rs_career": {
          "GP": 272,
          "PPG": 22.5,
          "RPG": 5.4,
          "APG": 8.0
        },
        "playoff_career": {
          "GP": 20,
          "PPG": 27.2,
          "RPG": 6.1,
          "APG": 7.8
        }
      }
    },
    "Bam Adebayo": {
      "player_id": 1628389,
      "gp": 78,
      "ppg": 18.1,
      "rpg": 9.6,
      "apg": 4.3,
      "spg": 1.3,
      "bpg": 0.7,
      "fg_pct": 48.5,
      "fg3_pct": 35.7,
      "ft_pct": 76.5,
      "ts_pct": 56.1,
      "usg_pct": 23.2,
      "pie": 13.7,
      "career": {
        "rs_career": {
          "GP": 640,
          "PPG": 16.2,
          "RPG": 9.0,
          "APG": 3.6
        },
        "playoff_career": {
          "GP": 78,
          "PPG": 16.4,
          "RPG": 9.2,
          "APG": 3.5
        }
      }
    },
    "Pascal Siakam": {
      "player_id": 1627783,
      "gp": 78,
      "ppg": 20.2,
      "rpg": 6.9,
      "apg": 3.4,
      "spg": 0.9,
      "bpg": 0.5,
      "fg_pct": 51.9,
      "fg3_pct": 38.9,
      "ft_pct": 73.4,
      "ts_pct": 59.9,
      "usg_pct": 23.7,
      "pie": 13.0,
      "career": {
        "rs_career": {
          "GP": 691,
          "PPG": 18.5,
          "RPG": 6.6,
          "APG": 3.6
        },
        "playoff_career": {
          "GP": 93,
          "PPG": 18.1,
          "RPG": 6.6,
          "APG": 3.2
        }
      }
    },
    "Tyrese Haliburton": {
      "player_id": 1630169,
      "gp": 73,
      "ppg": 18.6,
      "rpg": 3.5,
      "apg": 9.2,
      "spg": 1.4,
      "bpg": 0.7,
      "fg_pct": 47.3,
      "fg3_pct": 38.8,
      "ft_pct": 85.1,
      "ts_pct": 61.6,
      "usg_pct": 21.0,
      "pie": 14.3,
      "career": {
        "rs_career": {
          "GP": 333,
          "PPG": 17.5,
          "RPG": 3.7,
          "APG": 8.8
        },
        "playoff_career": {
          "GP": 38,
          "PPG": 17.9,
          "RPG": 5.1,
          "APG": 8.4
        }
      }
    },
    "LaMelo Ball": {
      "player_id": 1630163,
      "gp": 47,
      "ppg": 25.2,
      "rpg": 4.9,
      "apg": 7.4,
      "spg": 1.1,
      "bpg": 0.3,
      "fg_pct": 40.5,
      "fg3_pct": 33.9,
      "ft_pct": 84.3,
      "ts_pct": 53.6,
      "usg_pct": 34.2,
      "pie": 12.7,
      "career": {
        "rs_career": {
          "GP": 303,
          "PPG": 20.8,
          "RPG": 5.7,
          "APG": 7.3
        },
        "playoff_career": null
      }
    },
    "Zach LaVine": {
      "player_id": 203897,
      "gp": 74,
      "ppg": 23.3,
      "rpg": 4.3,
      "apg": 4.2,
      "spg": 0.8,
      "bpg": 0.2,
      "fg_pct": 51.1,
      "fg3_pct": 44.6,
      "ft_pct": 82.5,
      "ts_pct": 63.9,
      "usg_pct": 25.1,
      "pie": 11.5,
      "career": {
        "rs_career": {
          "GP": 693,
          "PPG": 20.7,
          "RPG": 4.0,
          "APG": 3.9
        },
        "playoff_career": {
          "GP": 4,
          "PPG": 19.2,
          "RPG": 5.2,
          "APG": 6.0
        }
      }
    },
    "Devin Booker": {
      "player_id": 1626164,
      "gp": 75,
      "ppg": 25.6,
      "rpg": 4.1,
      "apg": 7.1,
      "spg": 0.9,
      "bpg": 0.2,
      "fg_pct": 46.1,
      "fg3_pct": 33.2,
      "ft_pct": 89.4,
      "ts_pct": 58.9,
      "usg_pct": 28.5,
      "pie": 12.2,
      "career": {
        "rs_career": {
          "GP": 737,
          "PPG": 24.6,
          "RPG": 4.0,
          "APG": 5.3
        },
        "playoff_career": {
          "GP": 51,
          "PPG": 27.5,
          "RPG": 5.0,
          "APG": 5.2
        }
      }
    },
    "Julius Randle": {
      "player_id": 203944,
      "gp": 69,
      "ppg": 18.7,
      "rpg": 7.1,
      "apg": 4.7,
      "spg": 0.7,
      "bpg": 0.2,
      "fg_pct": 48.5,
      "fg3_pct": 34.4,
      "ft_pct": 80.6,
      "ts_pct": 59.3,
      "usg_pct": 24.6,
      "pie": 12.4,
      "career": {
        "rs_career": {
          "GP": 789,
          "PPG": 19.2,
          "RPG": 8.9,
          "APG": 3.9
        },
        "playoff_career": {
          "GP": 42,
          "PPG": 18.4,
          "RPG": 7.6,
          "APG": 3.9
        }
      }
    },
    "Paolo Banchero": {
      "player_id": 1631094,
      "gp": 46,
      "ppg": 25.9,
      "rpg": 7.5,
      "apg": 4.8,
      "spg": 0.8,
      "bpg": 0.6,
      "fg_pct": 45.2,
      "fg3_pct": 32.0,
      "ft_pct": 72.7,
      "ts_pct": 55.1,
      "usg_pct": 33.0,
      "pie": 15.7,
      "career": {
        "rs_career": {
          "GP": 270,
          "PPG": 22.3,
          "RPG": 7.4,
          "APG": 4.8
        },
        "playoff_career": {
          "GP": 19,
          "PPG": 27.4,
          "RPG": 8.7,
          "APG": 4.9
        }
      }
    },
    "Darius Garland": {
      "player_id": 1629636,
      "gp": 75,
      "ppg": 20.6,
      "rpg": 2.9,
      "apg": 6.7,
      "spg": 1.2,
      "bpg": 0.1,
      "fg_pct": 47.2,
      "fg3_pct": 40.1,
      "ft_pct": 87.8,
      "ts_pct": 60.0,
      "usg_pct": 26.5,
      "pie": 12.6,
      "career": {
        "rs_career": {
          "GP": 427,
          "PPG": 18.9,
          "RPG": 2.6,
          "APG": 6.7
        },
        "playoff_career": {
          "GP": 22,
          "PPG": 17.3,
          "RPG": 2.9,
          "APG": 5.5
        }
      }
    }
  }
};
