// Auto-generated by mitchell_profile.py — do not edit manually
const MITCHELL_DATA = {
  "season": "2025-26",
  "ordered": [
    "Nikola Jokic",
    "Shai Gilgeous-Alexander",
    "Giannis Antetokounmpo",
    "Luka Doncic",
    "Jayson Tatum",
    "Victor Wembanyama",
    "Anthony Edwards",
    "Stephen Curry",
    "Kevin Durant",
    "LeBron James",
    "Anthony Davis",
    "Jalen Brunson",
    "Jaylen Brown",
    "Tyrese Maxey",
    "Karl-Anthony Towns",
    "De'Aaron Fox",
    "Donovan Mitchell",
    "Cade Cunningham",
    "Bam Adebayo",
    "Pascal Siakam",
    "LaMelo Ball",
    "Zach LaVine",
    "Devin Booker",
    "Julius Randle",
    "Paolo Banchero",
    "Darius Garland"
  ],
  "players": {
    "Nikola Jokic": {
      "player_id": 203999,
      "team": "DEN",
      "gp": 65,
      "ppg": 27.7,
      "rpg": 12.9,
      "apg": 10.7,
      "spg": 1.4,
      "bpg": 0.8,
      "fg_pct": 56.9,
      "fg3_pct": 38.0,
      "ft_pct": 83.1,
      "ts_pct": 67.0,
      "usg_pct": 28.9,
      "pie": 21.3,
      "career": {
        "rs_career": {
          "GP": 810,
          "PPG": 22.2,
          "RPG": 11.1,
          "APG": 7.5
        },
        "playoff_career": {
          "GP": 100,
          "PPG": 27.4,
          "RPG": 12.4,
          "APG": 7.7
        }
      }
    },
    "Shai Gilgeous-Alexander": {
      "player_id": 1628983,
      "team": "OKC",
      "gp": 68,
      "ppg": 31.1,
      "rpg": 4.3,
      "apg": 6.6,
      "spg": 1.4,
      "bpg": 0.8,
      "fg_pct": 55.3,
      "fg3_pct": 38.6,
      "ft_pct": 87.9,
      "ts_pct": 66.5,
      "usg_pct": 32.3,
      "pie": 20.7,
      "career": {
        "rs_career": {
          "GP": 530,
          "PPG": 25.3,
          "RPG": 4.7,
          "APG": 5.3
        },
        "playoff_career": {
          "GP": 61,
          "PPG": 26.2,
          "RPG": 4.8,
          "APG": 6.2
        }
      }
    },
    "Giannis Antetokounmpo": {
      "player_id": 203507,
      "team": "MIL",
      "gp": 36,
      "ppg": 27.6,
      "rpg": 9.8,
      "apg": 5.4,
      "spg": 0.9,
      "bpg": 0.7,
      "fg_pct": 62.4,
      "fg3_pct": 33.3,
      "ft_pct": 65.0,
      "ts_pct": 65.8,
      "usg_pct": 35.8,
      "pie": 21.3,
      "career": {
        "rs_career": {
          "GP": 895,
          "PPG": 24.1,
          "RPG": 9.9,
          "APG": 5.0
        },
        "playoff_career": {
          "GP": 84,
          "PPG": 27.0,
          "RPG": 12.2,
          "APG": 5.3
        }
      }
    },
    "Luka Doncic": {
      "player_id": 1629029,
      "team": "LAL",
      "gp": 64,
      "ppg": 33.5,
      "rpg": 7.7,
      "apg": 8.3,
      "spg": 1.6,
      "bpg": 0.5,
      "fg_pct": 47.6,
      "fg3_pct": 36.6,
      "ft_pct": 78.0,
      "ts_pct": 61.6,
      "usg_pct": 36.8,
      "pie": 18.8,
      "career": {
        "rs_career": {
          "GP": 514,
          "PPG": 29.2,
          "RPG": 8.5,
          "APG": 8.2
        },
        "playoff_career": {
          "GP": 55,
          "PPG": 30.9,
          "RPG": 9.2,
          "APG": 7.8
        }
      }
    },
    "Jayson Tatum": {
      "player_id": 1628369,
      "team": "BOS",
      "gp": 16,
      "ppg": 21.8,
      "rpg": 10.0,
      "apg": 5.3,
      "spg": 1.4,
      "bpg": 0.2,
      "fg_pct": 41.1,
      "fg3_pct": 32.9,
      "ft_pct": 82.3,
      "ts_pct": 54.1,
      "usg_pct": 29.0,
      "pie": 15.9,
      "career": {
        "rs_career": {
          "GP": 601,
          "PPG": 23.5,
          "RPG": 7.4,
          "APG": 3.9
        },
        "playoff_career": {
          "GP": 127,
          "PPG": 24.2,
          "RPG": 8.3,
          "APG": 5.0
        }
      }
    },
    "Victor Wembanyama": {
      "player_id": 1641705,
      "team": "SAS",
      "gp": 64,
      "ppg": 25.0,
      "rpg": 11.5,
      "apg": 3.1,
      "spg": 1.0,
      "bpg": 3.1,
      "fg_pct": 51.2,
      "fg3_pct": 34.9,
      "ft_pct": 82.7,
      "ts_pct": 62.6,
      "usg_pct": 31.6,
      "pie": 20.9,
      "career": {
        "rs_career": {
          "GP": 181,
          "PPG": 23.4,
          "RPG": 11.0,
          "APG": 3.5
        },
        "playoff_career": {
          "GP": 17,
          "PPG": 23.2,
          "RPG": 10.8,
          "APG": 2.7
        }
      }
    },
    "Anthony Edwards": {
      "player_id": 1630162,
      "team": "MIN",
      "gp": 61,
      "ppg": 28.8,
      "rpg": 5.0,
      "apg": 3.7,
      "spg": 1.4,
      "bpg": 0.8,
      "fg_pct": 48.9,
      "fg3_pct": 39.9,
      "ft_pct": 79.6,
      "ts_pct": 61.7,
      "usg_pct": 30.9,
      "pie": 14.5,
      "career": {
        "rs_career": {
          "GP": 442,
          "PPG": 24.6,
          "RPG": 5.2,
          "APG": 4.1
        },
        "playoff_career": {
          "GP": 52,
          "PPG": 25.9,
          "RPG": 6.5,
          "APG": 4.9
        }
      }
    },
    "Stephen Curry": {
      "player_id": 201939,
      "team": "GSW",
      "gp": 43,
      "ppg": 26.6,
      "rpg": 3.6,
      "apg": 4.7,
      "spg": 1.1,
      "bpg": 0.4,
      "fg_pct": 46.8,
      "fg3_pct": 39.3,
      "ft_pct": 92.3,
      "ts_pct": 63.7,
      "usg_pct": 30.8,
      "pie": 14.6,
      "career": {
        "rs_career": {
          "GP": 1069,
          "PPG": 24.8,
          "RPG": 4.7,
          "APG": 6.3
        },
        "playoff_career": {
          "GP": 155,
          "PPG": 26.8,
          "RPG": 5.3,
          "APG": 6.1
        }
      }
    },
    "Kevin Durant": {
      "player_id": 201142,
      "team": "HOU",
      "gp": 78,
      "ppg": 26.0,
      "rpg": 5.5,
      "apg": 4.8,
      "spg": 0.8,
      "bpg": 0.9,
      "fg_pct": 52.0,
      "fg3_pct": 41.3,
      "ft_pct": 87.4,
      "ts_pct": 64.1,
      "usg_pct": 26.3,
      "pie": 15.0,
      "career": {
        "rs_career": {
          "GP": 1201,
          "PPG": 27.1,
          "RPG": 6.9,
          "APG": 4.4
        },
        "playoff_career": {
          "GP": 171,
          "PPG": 29.3,
          "RPG": 7.8,
          "APG": 4.2
        }
      }
    },
    "LeBron James": {
      "player_id": 2544,
      "team": "LAL",
      "gp": 60,
      "ppg": 20.9,
      "rpg": 6.1,
      "apg": 7.2,
      "spg": 1.2,
      "bpg": 0.6,
      "fg_pct": 51.5,
      "fg3_pct": 31.7,
      "ft_pct": 73.7,
      "ts_pct": 59.4,
      "usg_pct": 26.2,
      "pie": 15.4,
      "career": {
        "rs_career": {
          "GP": 1622,
          "PPG": 26.8,
          "RPG": 7.5,
          "APG": 7.4
        },
        "playoff_career": {
          "GP": 302,
          "PPG": 28.2,
          "RPG": 8.9,
          "APG": 7.2
        }
      }
    },
    "Anthony Davis": {
      "player_id": 203076,
      "team": "WAS",
      "gp": 20,
      "ppg": 20.4,
      "rpg": 11.1,
      "apg": 2.8,
      "spg": 1.1,
      "bpg": 1.7,
      "fg_pct": 50.6,
      "fg3_pct": 27.0,
      "ft_pct": 72.8,
      "ts_pct": 55.1,
      "usg_pct": 27.2,
      "pie": 15.1,
      "career": {
        "rs_career": {
          "GP": 807,
          "PPG": 24.0,
          "RPG": 10.7,
          "APG": 2.6
        },
        "playoff_career": {
          "GP": 60,
          "PPG": 26.1,
          "RPG": 11.8,
          "APG": 2.8
        }
      }
    },
    "Jalen Brunson": {
      "player_id": 1628973,
      "team": "NYK",
      "gp": 74,
      "ppg": 26.0,
      "rpg": 3.3,
      "apg": 6.8,
      "spg": 0.8,
      "bpg": 0.1,
      "fg_pct": 46.7,
      "fg3_pct": 36.9,
      "ft_pct": 84.1,
      "ts_pct": 58.0,
      "usg_pct": 29.6,
      "pie": 13.5,
      "career": {
        "rs_career": {
          "GP": 561,
          "PPG": 19.2,
          "RPG": 3.2,
          "APG": 5.3
        },
        "playoff_career": {
          "GP": 81,
          "PPG": 25.6,
          "RPG": 3.7,
          "APG": 5.6
        }
      }
    },
    "Jaylen Brown": {
      "player_id": 1627759,
      "team": "BOS",
      "gp": 71,
      "ppg": 28.7,
      "rpg": 6.9,
      "apg": 5.1,
      "spg": 1.0,
      "bpg": 0.4,
      "fg_pct": 47.7,
      "fg3_pct": 34.7,
      "ft_pct": 79.5,
      "ts_pct": 57.3,
      "usg_pct": 35.1,
      "pie": 15.2,
      "career": {
        "rs_career": {
          "GP": 674,
          "PPG": 20.0,
          "RPG": 5.5,
          "APG": 2.9
        },
        "playoff_career": {
          "GP": 142,
          "PPG": 19.6,
          "RPG": 5.7,
          "APG": 2.6
        }
      }
    },
    "Tyrese Maxey": {
      "player_id": 1630178,
      "team": "PHI",
      "gp": 70,
      "ppg": 28.3,
      "rpg": 4.1,
      "apg": 6.6,
      "spg": 1.9,
      "bpg": 0.8,
      "fg_pct": 46.2,
      "fg3_pct": 36.7,
      "ft_pct": 89.2,
      "ts_pct": 58.8,
      "usg_pct": 28.6,
      "pie": 15.0,
      "career": {
        "rs_career": {
          "GP": 388,
          "PPG": 21.1,
          "RPG": 3.2,
          "APG": 4.8
        },
        "playoff_career": {
          "GP": 52,
          "PPG": 19.1,
          "RPG": 3.7,
          "APG": 3.7
        }
      }
    },
    "Karl-Anthony Towns": {
      "player_id": 1626157,
      "team": "NYK",
      "gp": 75,
      "ppg": 20.1,
      "rpg": 11.9,
      "apg": 3.0,
      "spg": 0.9,
      "bpg": 0.5,
      "fg_pct": 50.1,
      "fg3_pct": 36.8,
      "ft_pct": 85.8,
      "ts_pct": 61.9,
      "usg_pct": 25.1,
      "pie": 15.4,
      "career": {
        "rs_career": {
          "GP": 720,
          "PPG": 22.8,
          "RPG": 11.1,
          "APG": 3.1
        },
        "playoff_career": {
          "GP": 64,
          "PPG": 19.2,
          "RPG": 10.7,
          "APG": 2.8
        }
      }
    },
    "De'Aaron Fox": {
      "player_id": 1628368,
      "team": "SAS",
      "gp": 72,
      "ppg": 18.6,
      "rpg": 3.8,
      "apg": 6.2,
      "spg": 1.2,
      "bpg": 0.3,
      "fg_pct": 48.6,
      "fg3_pct": 33.2,
      "ft_pct": 76.0,
      "ts_pct": 57.8,
      "usg_pct": 24.2,
      "pie": 11.7,
      "career": {
        "rs_career": {
          "GP": 603,
          "PPG": 21.1,
          "RPG": 3.9,
          "APG": 6.1
        },
        "playoff_career": {
          "GP": 23,
          "PPG": 19.8,
          "RPG": 4.4,
          "APG": 6.5
        }
      }
    },
    "Donovan Mitchell": {
      "player_id": 1628378,
      "team": "CLE",
      "gp": 70,
      "ppg": 27.9,
      "rpg": 4.5,
      "apg": 5.7,
      "spg": 1.5,
      "bpg": 0.3,
      "fg_pct": 48.3,
      "fg3_pct": 36.4,
      "ft_pct": 86.5,
      "ts_pct": 61.3,
      "usg_pct": 31.1,
      "pie": 15.2,
      "career": {
        "rs_career": {
          "GP": 609,
          "PPG": 25.1,
          "RPG": 4.3,
          "APG": 4.8
        },
        "playoff_career": {
          "GP": 81,
          "PPG": 27.8,
          "RPG": 5.0,
          "APG": 4.4
        }
      },
      "clutch": {
        "s0": {
          "label": "2025-26",
          "gp": 70,
          "ppg": 27.9,
          "fg_pct": 48.3,
          "w_pct": 64.3
        },
        "s1": {
          "label": "2025-26",
          "gp": 23,
          "ppg": 1.9,
          "fg_pct": 39.0,
          "w_pct": 39.1
        },
        "s2": {
          "label": "2025-26",
          "gp": 19,
          "ppg": 1.9,
          "fg_pct": 45.2,
          "w_pct": 36.8
        },
        "s3": {
          "label": "2025-26",
          "gp": 14,
          "ppg": 1.4,
          "fg_pct": 35.3,
          "w_pct": 28.6
        },
        "s4": {
          "label": "2025-26",
          "gp": 9,
          "ppg": 0.4,
          "fg_pct": 20.0,
          "w_pct": 22.2
        },
        "s5": {
          "label": "2025-26",
          "gp": 9,
          "ppg": 0.4,
          "fg_pct": 25.0,
          "w_pct": 22.2
        },
        "s6": {
          "label": "2025-26",
          "gp": 34,
          "ppg": 2.6,
          "fg_pct": 40.6,
          "w_pct": 58.8
        },
        "s7": {
          "label": "2025-26",
          "gp": 28,
          "ppg": 2.5,
          "fg_pct": 42.0,
          "w_pct": 57.1
        },
        "s8": {
          "label": "2025-26",
          "gp": 25,
          "ppg": 1.6,
          "fg_pct": 40.7,
          "w_pct": 60.0
        },
        "s9": {
          "label": "2025-26",
          "gp": 17,
          "ppg": 0.6,
          "fg_pct": 37.5,
          "w_pct": 58.8
        },
        "s10": {
          "label": "2025-26",
          "gp": 13,
          "ppg": 0.6,
          "fg_pct": 40.0,
          "w_pct": 46.2
        }
      }
    },
    "Cade Cunningham": {
      "player_id": 1630595,
      "team": "DET",
      "gp": 64,
      "ppg": 23.9,
      "rpg": 5.5,
      "apg": 9.9,
      "spg": 1.4,
      "bpg": 0.8,
      "fg_pct": 46.1,
      "fg3_pct": 34.2,
      "ft_pct": 81.2,
      "ts_pct": 56.4,
      "usg_pct": 29.6,
      "pie": 15.9,
      "career": {
        "rs_career": {
          "GP": 272,
          "PPG": 22.5,
          "RPG": 5.4,
          "APG": 8.0
        },
        "playoff_career": {
          "GP": 20,
          "PPG": 27.2,
          "RPG": 6.1,
          "APG": 7.8
        }
      }
    },
    "Bam Adebayo": {
      "player_id": 1628389,
      "team": "MIA",
      "gp": 73,
      "ppg": 20.1,
      "rpg": 10.0,
      "apg": 3.2,
      "spg": 1.2,
      "bpg": 0.7,
      "fg_pct": 44.2,
      "fg3_pct": 31.8,
      "ft_pct": 77.8,
      "ts_pct": 55.1,
      "usg_pct": 24.8,
      "pie": 13.8,
      "career": {
        "rs_career": {
          "GP": 640,
          "PPG": 16.2,
          "RPG": 9.0,
          "APG": 3.6
        },
        "playoff_career": {
          "GP": 78,
          "PPG": 16.4,
          "RPG": 9.2,
          "APG": 3.5
        }
      }
    },
    "Pascal Siakam": {
      "player_id": 1627783,
      "team": "IND",
      "gp": 62,
      "ppg": 24.0,
      "rpg": 6.6,
      "apg": 3.8,
      "spg": 1.1,
      "bpg": 0.4,
      "fg_pct": 48.4,
      "fg3_pct": 35.8,
      "ft_pct": 69.3,
      "ts_pct": 56.2,
      "usg_pct": 29.2,
      "pie": 13.0,
      "career": {
        "rs_career": {
          "GP": 691,
          "PPG": 18.5,
          "RPG": 6.6,
          "APG": 3.6
        },
        "playoff_career": {
          "GP": 93,
          "PPG": 18.1,
          "RPG": 6.6,
          "APG": 3.2
        }
      }
    },
    "LaMelo Ball": {
      "player_id": 1630163,
      "team": "CHA",
      "gp": 72,
      "ppg": 20.1,
      "rpg": 4.8,
      "apg": 7.1,
      "spg": 1.2,
      "bpg": 0.3,
      "fg_pct": 40.7,
      "fg3_pct": 36.8,
      "ft_pct": 89.9,
      "ts_pct": 54.6,
      "usg_pct": 30.6,
      "pie": 13.4,
      "career": {
        "rs_career": {
          "GP": 303,
          "PPG": 20.8,
          "RPG": 5.7,
          "APG": 7.3
        },
        "playoff_career": null
      }
    },
    "Zach LaVine": {
      "player_id": 203897,
      "team": "SAC",
      "gp": 39,
      "ppg": 19.2,
      "rpg": 2.8,
      "apg": 2.3,
      "spg": 0.7,
      "bpg": 0.3,
      "fg_pct": 47.9,
      "fg3_pct": 39.0,
      "ft_pct": 88.0,
      "ts_pct": 61.4,
      "usg_pct": 23.4,
      "pie": 9.6,
      "career": {
        "rs_career": {
          "GP": 693,
          "PPG": 20.7,
          "RPG": 4.0,
          "APG": 3.9
        },
        "playoff_career": {
          "GP": 4,
          "PPG": 19.2,
          "RPG": 5.2,
          "APG": 6.0
        }
      }
    },
    "Devin Booker": {
      "player_id": 1626164,
      "team": "PHX",
      "gp": 64,
      "ppg": 26.1,
      "rpg": 3.9,
      "apg": 6.0,
      "spg": 0.8,
      "bpg": 0.3,
      "fg_pct": 45.6,
      "fg3_pct": 33.0,
      "ft_pct": 87.3,
      "ts_pct": 58.5,
      "usg_pct": 30.7,
      "pie": 14.2,
      "career": {
        "rs_career": {
          "GP": 737,
          "PPG": 24.6,
          "RPG": 4.0,
          "APG": 5.3
        },
        "playoff_career": {
          "GP": 51,
          "PPG": 27.5,
          "RPG": 5.0,
          "APG": 5.2
        }
      }
    },
    "Julius Randle": {
      "player_id": 203944,
      "team": "MIN",
      "gp": 79,
      "ppg": 21.1,
      "rpg": 6.7,
      "apg": 5.0,
      "spg": 1.1,
      "bpg": 0.2,
      "fg_pct": 48.1,
      "fg3_pct": 31.5,
      "ft_pct": 80.2,
      "ts_pct": 58.5,
      "usg_pct": 25.8,
      "pie": 12.8,
      "career": {
        "rs_career": {
          "GP": 789,
          "PPG": 19.2,
          "RPG": 8.9,
          "APG": 3.9
        },
        "playoff_career": {
          "GP": 42,
          "PPG": 18.4,
          "RPG": 7.6,
          "APG": 3.9
        }
      }
    },
    "Paolo Banchero": {
      "player_id": 1631094,
      "team": "ORL",
      "gp": 72,
      "ppg": 22.2,
      "rpg": 8.4,
      "apg": 5.2,
      "spg": 0.7,
      "bpg": 0.6,
      "fg_pct": 45.9,
      "fg3_pct": 30.5,
      "ft_pct": 77.5,
      "ts_pct": 56.6,
      "usg_pct": 27.4,
      "pie": 13.8,
      "career": {
        "rs_career": {
          "GP": 270,
          "PPG": 22.3,
          "RPG": 7.4,
          "APG": 4.8
        },
        "playoff_career": {
          "GP": 19,
          "PPG": 27.4,
          "RPG": 8.7,
          "APG": 4.9
        }
      }
    },
    "Darius Garland": {
      "player_id": 1629636,
      "team": "LAC",
      "gp": 45,
      "ppg": 18.8,
      "rpg": 2.4,
      "apg": 6.7,
      "spg": 1.0,
      "bpg": 0.2,
      "fg_pct": 46.0,
      "fg3_pct": 39.6,
      "ft_pct": 86.1,
      "ts_pct": 58.2,
      "usg_pct": 26.6,
      "pie": 11.2,
      "career": {
        "rs_career": {
          "GP": 427,
          "PPG": 18.9,
          "RPG": 2.6,
          "APG": 6.7
        },
        "playoff_career": {
          "GP": 22,
          "PPG": 17.3,
          "RPG": 2.9,
          "APG": 5.5
        }
      }
    }
  },
  "ranking": [
    {
      "rank": 1,
      "name": "Nikola Jokic",
      "team": "DEN",
      "tier": "lock",
      "score": 95.2,
      "ppg": 27.7,
      "ts_pct": 67.0,
      "pie": 21.3,
      "po_ppg": 27.4,
      "po_gp": 100,
      "is_mitchell": false
    },
    {
      "rank": 2,
      "name": "Shai Gilgeous-Alexander",
      "team": "OKC",
      "tier": "lock",
      "score": 94.0,
      "ppg": 31.1,
      "ts_pct": 66.5,
      "pie": 20.7,
      "po_ppg": 26.2,
      "po_gp": 61,
      "is_mitchell": false
    },
    {
      "rank": 3,
      "name": "Luka Doncic",
      "team": "LAL",
      "tier": "lock",
      "score": 90.6,
      "ppg": 33.5,
      "ts_pct": 61.6,
      "pie": 18.8,
      "po_ppg": 30.9,
      "po_gp": 55,
      "is_mitchell": false
    },
    {
      "rank": 4,
      "name": "Kevin Durant",
      "team": "HOU",
      "tier": "lock",
      "score": 86.9,
      "ppg": 26.0,
      "ts_pct": 64.1,
      "pie": 15.0,
      "po_ppg": 29.3,
      "po_gp": 171,
      "is_mitchell": false
    },
    {
      "rank": 5,
      "name": "Victor Wembanyama",
      "team": "SAS",
      "tier": "lock",
      "score": 84.3,
      "ppg": 25.0,
      "ts_pct": 62.6,
      "pie": 20.9,
      "po_ppg": 23.2,
      "po_gp": 17,
      "is_mitchell": false
    },
    {
      "rank": 6,
      "name": "Donovan Mitchell",
      "team": "CLE",
      "tier": "lock",
      "score": 82.9,
      "ppg": 27.9,
      "ts_pct": 61.3,
      "pie": 15.2,
      "po_ppg": 27.8,
      "po_gp": 81,
      "is_mitchell": true
    },
    {
      "rank": 7,
      "name": "LeBron James",
      "team": "LAL",
      "tier": "tier",
      "score": 79.4,
      "ppg": 20.9,
      "ts_pct": 59.4,
      "pie": 15.4,
      "po_ppg": 28.2,
      "po_gp": 302,
      "is_mitchell": false
    },
    {
      "rank": 8,
      "name": "Jaylen Brown",
      "team": "BOS",
      "tier": "tier",
      "score": 79.4,
      "ppg": 28.7,
      "ts_pct": 57.3,
      "pie": 15.2,
      "po_ppg": 19.6,
      "po_gp": 142,
      "is_mitchell": false
    },
    {
      "rank": 9,
      "name": "Anthony Edwards",
      "team": "MIN",
      "tier": "tier",
      "score": 78.8,
      "ppg": 28.8,
      "ts_pct": 61.7,
      "pie": 14.5,
      "po_ppg": 25.9,
      "po_gp": 52,
      "is_mitchell": false
    },
    {
      "rank": 10,
      "name": "Devin Booker",
      "team": "PHX",
      "tier": "tier",
      "score": 75.5,
      "ppg": 26.1,
      "ts_pct": 58.5,
      "pie": 14.2,
      "po_ppg": 27.5,
      "po_gp": 51,
      "is_mitchell": false
    },
    {
      "rank": 11,
      "name": "Jalen Brunson",
      "team": "NYK",
      "tier": "tier",
      "score": 75.3,
      "ppg": 26.0,
      "ts_pct": 58.0,
      "pie": 13.5,
      "po_ppg": 25.6,
      "po_gp": 81,
      "is_mitchell": false
    },
    {
      "rank": 12,
      "name": "Tyrese Maxey",
      "team": "PHI",
      "tier": "tier",
      "score": 75.3,
      "ppg": 28.3,
      "ts_pct": 58.8,
      "pie": 15.0,
      "po_ppg": 19.1,
      "po_gp": 52,
      "is_mitchell": false
    },
    {
      "rank": 13,
      "name": "Karl-Anthony Towns",
      "team": "NYK",
      "tier": "chase",
      "score": 74.7,
      "ppg": 20.1,
      "ts_pct": 61.9,
      "pie": 15.4,
      "po_ppg": 19.2,
      "po_gp": 64,
      "is_mitchell": false
    },
    {
      "rank": 14,
      "name": "Cade Cunningham",
      "team": "DET",
      "tier": "chase",
      "score": 73.4,
      "ppg": 23.9,
      "ts_pct": 56.4,
      "pie": 15.9,
      "po_ppg": 27.2,
      "po_gp": 20,
      "is_mitchell": false
    },
    {
      "rank": 15,
      "name": "Paolo Banchero",
      "team": "ORL",
      "tier": "chase",
      "score": 69.1,
      "ppg": 22.2,
      "ts_pct": 56.6,
      "pie": 13.8,
      "po_ppg": 27.4,
      "po_gp": 19,
      "is_mitchell": false
    },
    {
      "rank": 16,
      "name": "Pascal Siakam",
      "team": "IND",
      "tier": "chase",
      "score": 69.0,
      "ppg": 24.0,
      "ts_pct": 56.2,
      "pie": 13.0,
      "po_ppg": 18.1,
      "po_gp": 93,
      "is_mitchell": false
    },
    {
      "rank": 17,
      "name": "Bam Adebayo",
      "team": "MIA",
      "tier": "chase",
      "score": 66.3,
      "ppg": 20.1,
      "ts_pct": 55.1,
      "pie": 13.8,
      "po_ppg": 16.4,
      "po_gp": 78,
      "is_mitchell": false
    },
    {
      "rank": 18,
      "name": "Julius Randle",
      "team": "MIN",
      "tier": "chase",
      "score": 66.2,
      "ppg": 21.1,
      "ts_pct": 58.5,
      "pie": 12.8,
      "po_ppg": 18.4,
      "po_gp": 42,
      "is_mitchell": false
    },
    {
      "rank": 19,
      "name": "De'Aaron Fox",
      "team": "SAS",
      "tier": "chase",
      "score": 61.6,
      "ppg": 18.6,
      "ts_pct": 57.8,
      "pie": 11.7,
      "po_ppg": 19.8,
      "po_gp": 23,
      "is_mitchell": false
    },
    {
      "rank": 20,
      "name": "Darius Garland",
      "team": "LAC",
      "tier": "chase",
      "score": 55.5,
      "ppg": 18.8,
      "ts_pct": 58.2,
      "pie": 11.2,
      "po_ppg": 17.3,
      "po_gp": 22,
      "is_mitchell": false
    },
    {
      "rank": 21,
      "name": "LaMelo Ball",
      "team": "CHA",
      "tier": "chase",
      "score": 53.4,
      "ppg": 20.1,
      "ts_pct": 54.6,
      "pie": 13.4,
      "po_ppg": null,
      "po_gp": 0,
      "is_mitchell": false
    }
  ],
  "mitchell_rank": 6,
  "lab_weights": {
    "impact": 0.35,
    "scoring": 0.18,
    "efficiency": 0.12,
    "playoffs": 0.2,
    "availability": 0.15
  }
};
